import { createStore } from "vuex";

export default createStore({
  state: {
    icons: {
      time: "fa fa-clock",
      amountـofـoil: "fa fa-hourglass-start",
      driver_id: "fa fa-at",
      object_id: "fa fa-at",
      type: "fa fa-truck",
      enginHours: "fa-regular fa-clock",
      engin_id: "fa-regular fa-list",
      engin_type: "fa fa-cogs",
      model: "fa-solid fa-car",
      tireـpressure: "fa fa-battery-half",
      gps_imei: "fa fa-at",
      amountـofـgas: "fa fa-hourglass-start",
      object_control: "fa fa-check-circle",
      odometer: "fa-solid fa-gauge",
      plate: "fa-regular fa-map",
      status: "fa-solid fa-wave-square",
      odometr: "fa fa-flag",
      mile_age: "fa fa-bicycle",
      altitude: "fa fa-flag",
      engin_status: "fa fa-check",
      address: "fa-regular fa-address-card",
      longitude: "fa fa-flag",
      latitude: "fa fa-flag",
      satellites: "fa fa-map",
      angle: "fa-solid fa-angle-right",
      nearestZone: "fa-solid fa-spinner",
      position: "fa-solid fa-location-dot",
      speed: "fa-solid fa-gauge-high",
      timePosition: "fa-regular fa-clock",
      timeServer: "fa-regular fa-clock",
      ingnition: "fa fa-flag",
      car: "fa fa-car",
      bus: "fa fa-bus",
      truck: "fa fa-truck",
      Bike: "fa fa-bicycle",
      motorcycle: "fa fa-motorcycle",
      on: "fa fa-eye",
      off: "fa fa-eye-slash",
      gprsPower: "fa fa-battery-half",
      gpsPower: "fa fa-battery-half",
      monitoringSystemOn: "fa fa-desktop",
      monitoringOrUpgradeStatus: "fa fa-desktop",
      UpgradeFlag: "fa fa-bolt",
      sendDataDelayTime: "fa fa-cloud-upload",
      checkGprsAntenaTimer: "fa fa-wifi",
      dataLoggerActive: "fa fa-bars",
      gpsSleepModeActive: "fa fa-eye-slash",
      gsmSleepModeActive: "fa fa-eye-slash",
      carDoorOpen1: "fa fa-car",
      carDoorOpen2: "fa fa-car",
      carSwitchOn: "fa fa-rocket",
      carWindowOpen: "fa fa-window-maximize",
      serverConnectionTime: "fa fa-clock",
      batteryVoltage: "fa fa-battery",
      inputVoltage: "fa fa-battery",
      upgradePort: "fa fa-code-fork",
      timeToSendDataToDevice: "fa fa-clock",
      dataTransmissionDelayWhenStopped: "fa fa-bar-chart",
      simcardCharge: "fa fa-bolt",
      numberOfRecordsStored: "fa fa-cloud-download",
      numberOfRecordsSentToServer: "fa fa-cloud-upload",
      frimwareVersion: "fa fa-v",
      simcardNumber: "fa fa-phone",
      sosMobileNumber1: "fa fa-phone",
      sosMobileNumber2: "fa fa-phone",
      sosMobileNumber3: "fa fa-phone",
      human: "fa fa-male",
      notUpdatedData: "fa fa-exclamation-circle",
    },
    commands: {
      enginOff: {
        message: "turn off the engin",
        code: 1,
      },
      enginOn: {
        message: "turn on the engin",
        code: 2,
      },
    },
  },
  mutations: {},
  getters: {},
  actions: {},
  modules: {},
});
